const { ethers, artifacts, network } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log(`👤 Deployer: ${deployer.address}`);
  console.log(`💰 Balance: ${ethers.utils.formatEther(await deployer.getBalance())} ETH`);

  // Deploy token
  const PollToken = await ethers.getContractFactory("PollToken");
  const token = await PollToken.deploy();
  await token.deployed();
  console.log(`✅ PollToken deployed at: ${token.address}`);

  // Deploy system
  const PollSystem = await ethers.getContractFactory("PollSystem");
  const pollSystem = await PollSystem.deploy(token.address, deployer.address);
  await pollSystem.deployed();
  console.log(`✅ PollSystem deployed at: ${pollSystem.address}`);

  // Send tokens to PollSystem
  await (await token.transfer(pollSystem.address, ethers.utils.parseEther("1000"))).wait();
  console.log(`💸 Sent 1000 POLL to PollSystem`);

  // Prepare paths
  const deploymentsDir = path.join(__dirname, "../deployments");
  const frontendEnvPath = path.join(__dirname, "../frontend/.env");
  const backendEnvPath = path.join(__dirname, "../backend/.env");

  fs.mkdirSync(deploymentsDir, { recursive: true });

  // Save deploy.json
  fs.writeFileSync(
    path.join(deploymentsDir, "deploy.json"),
    JSON.stringify({
      pollTokenAddress: token.address,
      pollSystemAddress: pollSystem.address,
      relayer: deployer.address,
      network: network.name,
      deployedAt: new Date().toISOString()
    }, null, 2)
  );

  // Save ABI as pure array
  const pollTokenArtifact = await artifacts.readArtifact("PollToken");
  fs.writeFileSync(
    path.join(deploymentsDir, "poll_token_abi.json"),
    JSON.stringify(pollTokenArtifact.abi, null, 2)
  );

  const pollSystemArtifact = await artifacts.readArtifact("PollSystem");
  fs.writeFileSync(
    path.join(deploymentsDir, "poll_system_abi.json"),
    JSON.stringify(pollSystemArtifact.abi, null, 2)
  );

  // Write backend .env
  fs.writeFileSync(backendEnvPath, `# Auto-generated by deploy.js
RPC_URL=http://127.0.0.1:8545
CONTRACT_ADDRESS=${pollSystem.address}
POLL_TOKEN_ADDRESS=${token.address}
PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
`.trim());

  // Write frontend .env ✨
  fs.writeFileSync(frontendEnvPath, `# Auto-generated by deploy.js
VITE_POLL_SYSTEM_ADDRESS=${pollSystem.address}
VITE_POLL_TOKEN_ADDRESS=${token.address}
VITE_BACKEND_API_URL=http://localhost:8000
`.trim());

  console.log("✅ Deployment complete! All .env and ABI files are in sync 🧩");
}

main().catch((err) => {
  console.error("❌ Deploy failed:", err);
  process.exit(1);
});